Silence own repo

diff --git a/.github/workflows/check_pr_label.yml b/.github/workflows/check_pr_label.yml
--- a/.github/workflows/check_pr_label.yml
+++ b/.github/workflows/check_pr_label.yml
@@ -1,18 +1,18 @@
-name: 🏷️ Check labels
-on:
-  pull_request:
-    types: [opened, labeled, unlabeled, synchronize, reopened]
-jobs:
-    check_labels:
-        name: 🏷️ Check valid labels
-        runs-on: ubuntu-latest
-        steps:
-            - name: Check valid labels
-              run: |
-                  labels=$(jq -r '.pull_request.labels[] | .name' ${{github.event_path }}  | grep 'pr:') 
-                  if [[ ! $labels ]]; then
-                    echo "::error::You need to provide one or more labels that starts with 'pr:'"
-                    exit 1
-                  fi
-                  exit 0
+# name: 🏷️ Check labels
+# on:
+#   pull_request:
+#     types: [opened, labeled, unlabeled, synchronize, reopened]
+# jobs:
+#     check_labels:
+#         name: 🏷️ Check valid labels
+#         runs-on: ubuntu-latest
+#         steps:
+#             - name: Check valid labels
+#               run: |
+#                   labels=$(jq -r '.pull_request.labels[] | .name' ${{github.event_path }}  | grep 'pr:') 
+#                   if [[ ! $labels ]]; then
+#                     echo "::error::You need to provide one or more labels that starts with 'pr:'"
+#                     exit 1
+#                   fi
+#                   exit 0
 
